### PR TITLE
Add origin check at JWT

### LINKED ISSUE #15: Check origin header
https://thecopenhagenbook.com/csrf

### PR DESCRIPTION
**Pull request by JBorrow**
Adds an additional origin check and stores the origin in the JWT. Fixes #15.

This should help prevent CSRF attacks, though the web frontend primarily uses GET requests anyway (for now at least, once we start adding update functionality we will need to do some POSTing).

### CODE REVIEW

**Comment by JBorrow** [comment]
Note: this doesn't work with GitHub login for right now as that sets Origin=None as the initial request header... Sigh.

**Comment by zonca** [comment]
@JBorrow isn't is possible to use an existing implementation like https://indominusbyte.github.io/fastapi-jwt-auth/configuration/csrf/ or https://pypi.org/project/fastapi-csrf-protect/?

**Comment by JBorrow** [comment]
In theory yes but I don't think we can use the double-cookie submit pattern (and don't need to actually as we can set httponly=True).

**Comment by zonca** [comment]
@JBorrow I see some prints, would it be useful to configure a logger based on `logging`?

It would be useful to explain in the README how to launch the fastapi dev server to have a running test instance of this for doing some manual tests of the API.

**Comment by JBorrow** [comment]
Sorry, I thought I'd removed all of the print statements. In a future PR I will be adding wider logging, and me and Jeremy will be refactoring this frontend stuff later this week to split it up a bit.

A little more context here: I'd ideally like to keep the web frontend as basic as we can whilst providing the functionality that people will need. In my opinion, the best way to do this is to try to keep every request as a base HTTP request (i.e. a request for an actual page) instead of handling things through an API and using frontend tech like React. That's obviously not the best move for other systems (like the map viewer) but the hippo frontend should be so simple that we can get away with it.

This then means that we don't have direct control over the headers that we send with the web request. Normally you include a message to the client that is a bearer token that is passed in the headers of the HTTP requests so that you don't need to include the username and password in every single request. JWTs are signed such that you know that you emitted them. We don't have access to that particular control flow, so instead I'm using a cookie to send the bearer token to/from the client and server.

There is one problem with using cookie-based authentication, and that's a cross-site attack. This is where on another site contains a malicious form that POSTs to your site. With that POST request, your cookie is included.

This is even more problematic when JS on malicious sites can send these requests automatically on behalf of your user. This can be mitigated by setting httponly=True in the cookie, which means it is only sent when the browser (not javascript) makes the HTTP request. We already do this.

However, there is still the problem of someone creating a fake form that one of our logged-in users thinks is legit. That form sends a POST request to our application, and was initiated by the user, and also includes the cookie... But we can use some information on where the request came from to try to limit the impact of these attacks. The browser will tell you what the `Origin` was for this (POST, not GET) request, and you can use that. There is also another header that tells you, according to the browser, whether this request originated outside your own domain. We use that new header here as for GitHub auth there is a GET request sandwiched in there that leaves the `Origin` header unset.

There's always the problem of a stolen cookie; someone could extract your cookie from your browser manually and then use it on their machine to access your application. But at that point they basically have unlimited access to the compromised machine and we're basically hosed anyway. We could attempt to mitigate further by only allowing a specific IP or something but this would be problematic for users who are switching between access points or mobile networks.

**Comment by JBorrow** [comment]
See #17 for logging

**Comment by JBorrow** [comment]
More information on development server is now available in the `main` branch `README.md`.

**Comment by zonca** [comment]
> More information on development server is now available in the `main` branch `README.md`.

can you also add how to authenticate and do a simple product query?

**Comment by JBorrow** [comment]
Sure! I added a little there. There's also a video in the dm-data-delivery slack channel. I'm wary of over-documenting at this stage as we may want to (significantly) change interfaces.

**Comment by JBorrow** [comment]
Currently for web the authenticated endpoint is /user. To login, go to /login. To logout, go to /logout. You should be able to authenticate with GitHub as you are part of the simonsobs org.

**Comment by zonca** [comment]
@JBorrow I put `  "web_allow_github_login": true,` into config.json, but I still don't get anything at `/user` or `/login`, do I need the github client and secret?

**Comment by JBorrow** [comment]
Sorry, I forgot about that. For GitHub login you would indeed need a GitHub client and secret. It may be easiest for you to just create your own (the name, etc., doesn't matter) and then you own those keys.

**Pull request merged**
